apiVersion: v1
kind: Service
metadata:
      name: amazon-service
spec:
   selector:
      app: amazon
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazon-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "rahulsaini.shop"
    http:
      paths:
      - path: /amazon
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
